# Generated by Django 4.1.5 on 2023-01-26 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Автор')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='titles', verbose_name='Обложка')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('ordered', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Заказы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('authorship', models.ManyToManyField(blank=True, related_name='authorship', to='my_books.author', verbose_name='Соавторство')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жанр')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Общая цена')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа')),
                ('active', models.BooleanField(default=False, verbose_name='Завершённый')),
                ('authorship', models.ManyToManyField(blank=True, to='my_books.author', verbose_name='Соавторство')),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_books.books', verbose_name='Книги')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('authorship', models.ManyToManyField(blank=True, to='my_books.author', verbose_name='Соавторство')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_books.books', verbose_name='Книга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_books.genres', verbose_name='Жанр'),
        ),
    ]
